language: php

php:
    - 5.6
    - 7.0
    - hhvm
    
matrix:
  allow_failures:
    - php: hhvm
    
addons:
  apt:
    packages:
    - dnsutils

script: 
    - phpunit --configuration tests/phpunit.xml --coverage-text --coverage-clover build/logs/clover.xml

before_script:
    - travis_retry composer self-update

before_install:
    - pip install --user codecov

after_success:
    - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
    - stable

